### ISSUE TITLE
You are teleported around when you spectate by a player

### ISSUE THREAD

**Issue by Palmidence** [Kratous/Issues#24]
If you /spectate, and follow a user around whilst the match is playing, you cannot get close to them otherwise you teleport anywhere from 2-6 blocks away from them. It's not a consistent bug, but it makes it hard to watch a rulebreaker when your camera angles freak out.

This is for PVP, all Minecraft versions affected.

**Comment by JayNZ** [comment]
Hi,

This isn't a bug, this is enforced to spectators to make sure they do not interact/get in the way of the game play. 

If you would like to watch/spectate a game, just keep your distance. 

Thanks.
